---
driver:
  name: podman

platforms:
  - name: debian13
    image: docker.io/dokken/debian-13:latest
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: debian12
    image: docker.io/dokken/debian-12:latest
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd

scenario:
  test_sequence:
    # - dependency
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
